home:
    path:     /
    defaults: { _controller: UmgConferenciaBundle:Default:index }

Evento_home:
    resource:	"@UmgConferenciaBundle/Controller/EventoController.php"
    type:	annotation

Alumno_home:
    resource:	"@UmgConferenciaBundle/Controller/AlumnoController.php"
    type:	annotation
#alumno

AlumnoEvento_home:
    resource:	"@UmgConferenciaBundle/Controller/AlumnoEventoController.php"
    type:	annotation

AlumnoPago_home:
    resource:   "@UmgConferenciaBundle/Controller/AlumnoPagoController.php"
    type:       annotation
#alumnopago

AlumnoRecuerdo_home:
    resource:   "@UmgConferenciaBundle/Controller/AlumnoRecuerdoController.php"
    type:       annotation
#alumnorecuerdo

ConferenciaAlumno_home:
    resource:   "@UmgConferenciaBundle/Controller/ConferenciaAlumnoController.php"
    type:       annotation
#conferenciaalumno

Conferenciasta_home:
    resource:   "@UmgConferenciaBundle/Controller/ConferencistumController.php"
    type:       annotation
#conferencista

Conferencia_home:
    resource:   "@UmgConferenciaBundle/Controller/ConferenciumController.php"
    type:       annotation
#conferencia

Recuerdo_home:
    resource:   "@UmgConferenciaBundle/Controller/RecuerdoController.php"
    type:       annotation
#recuerdo

Salon_home:
    resource:   "@UmgConferenciaBundle/Controller/SalonController.php"
    type:       annotation
#salon

Usuario_home:
    resource:   "@UmgConferenciaBundle/Controller/UsuarioController.php"
    type:       annotation
#usuario

cargararchivo_home:
    path:   /cargar
    defaults: {_controller: UmgConferenciaBundle:CargarArchivo:importar}

cargararchivo:
    path:   /{id}/import
    defaults: {_controller: UmgConferenciaBundle:CargarArchivo:index}

showarchivo:
    path:   /import/show
    defaults: {_controller: UmgConferenciaBundle:CargarArchivo:show}
