<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-04-27 18:40:59.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\ConferenciaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Umg\ConferenciaBundle\Entity\AlumnoPago
 *
 * @ORM\Entity()
 * @ORM\Table(name="AlumnoPago", indexes={@ORM\Index(name="fk_AlumnoPago_Alumno1_idx", columns={"Alumno_id"})})
 */
class AlumnoPago
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $Boleta;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Alumno_id;

    /**
     * @ORM\ManyToOne(targetEntity="Alumno", inversedBy="alumnoPagos")
     * @ORM\JoinColumn(name="Alumno_id", referencedColumnName="id")
     */
    protected $alumno;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Boleta.
     *
     * @param string $Boleta
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setBoleta($Boleta)
    {
        $this->Boleta = $Boleta;

        return $this;
    }

    /**
     * Get the value of Boleta.
     *
     * @return string
     */
    public function getBoleta()
    {
        return $this->Boleta;
    }

    /**
     * Set the value of Alumno_id.
     *
     * @param integer $Alumno_id
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setAlumnoId($Alumno_id)
    {
        $this->Alumno_id = $Alumno_id;

        return $this;
    }

    /**
     * Get the value of Alumno_id.
     *
     * @return integer
     */
    public function getAlumnoId()
    {
        return $this->Alumno_id;
    }

    /**
     * Set Alumno entity (many to one).
     *
     * @param \Umg\ConferenciaBundle\Entity\Alumno $alumno
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setAlumno(Alumno $alumno = null)
    {
        $this->alumno = $alumno;

        return $this;
    }

    /**
     * Get Alumno entity (many to one).
     *
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function getAlumno()
    {
        return $this->alumno;
    }

    public function __sleep()
    {
        return array('id', 'Boleta', 'Alumno_id');
    }
}