<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-16 11:57:28.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\ConferenciaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Umg\ConferenciaBundle\Entity\AlumnoRecuerdo
 *
 * @ORM\Entity()
 * @ORM\Table(name="AlumnoRecuerdo", indexes={@ORM\Index(name="fk_AlumnoRecuerdo_Alumno1_idx", columns={"Alumno_id"}), @ORM\Index(name="fk_AlumnoRecuerdo_Recuerdo1_idx", columns={"Recuerdo_id"}), @ORM\Index(name="fk_AlumnoRecuerdo_Usuario1_idx", columns={"Usuario_id"})})
 */
class AlumnoRecuerdo
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $FechaHora;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Alumno_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Recuerdo_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Usuario_id;

    /**
     * @ORM\ManyToOne(targetEntity="Alumno", inversedBy="alumnoRecuerdos")
     * @ORM\JoinColumn(name="Alumno_id", referencedColumnName="id")
     */
    protected $alumno;

    /**
     * @ORM\ManyToOne(targetEntity="Recuerdo", inversedBy="alumnoRecuerdos")
     * @ORM\JoinColumn(name="Recuerdo_id", referencedColumnName="id")
     */
    protected $recuerdo;

    /**
     * @ORM\ManyToOne(targetEntity="Usuario", inversedBy="alumnoRecuerdos")
     * @ORM\JoinColumn(name="Usuario_id", referencedColumnName="id")
     */
    protected $usuario;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\ConferenciaBundle\Entity\AlumnoRecuerdo
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of FechaHora.
     *
     * @param \DateTime $FechaHora
     * @return \Umg\ConferenciaBundle\Entity\AlumnoRecuerdo
     */
    public function setFechaHora($FechaHora)
    {
        $this->FechaHora = $FechaHora;

        return $this;
    }

    /**
     * Get the value of FechaHora.
     *
     * @return \DateTime
     */
    public function getFechaHora()
    {
        return $this->FechaHora;
    }

    /**
     * Set the value of Alumno_id.
     *
     * @param integer $Alumno_id
     * @return \Umg\ConferenciaBundle\Entity\AlumnoRecuerdo
     */
    public function setAlumnoId($Alumno_id)
    {
        $this->Alumno_id = $Alumno_id;

        return $this;
    }

    /**
     * Get the value of Alumno_id.
     *
     * @return integer
     */
    public function getAlumnoId()
    {
        return $this->Alumno_id;
    }

    /**
     * Set the value of Recuerdo_id.
     *
     * @param integer $Recuerdo_id
     * @return \Umg\ConferenciaBundle\Entity\AlumnoRecuerdo
     */
    public function setRecuerdoId($Recuerdo_id)
    {
        $this->Recuerdo_id = $Recuerdo_id;

        return $this;
    }

    /**
     * Get the value of Recuerdo_id.
     *
     * @return integer
     */
    public function getRecuerdoId()
    {
        return $this->Recuerdo_id;
    }

    /**
     * Set the value of Usuario_id.
     *
     * @param integer $Usuario_id
     * @return \Umg\ConferenciaBundle\Entity\AlumnoRecuerdo
     */
    public function setUsuarioId($Usuario_id)
    {
        $this->Usuario_id = $Usuario_id;

        return $this;
    }

    /**
     * Get the value of Usuario_id.
     *
     * @return integer
     */
    public function getUsuarioId()
    {
        return $this->Usuario_id;
    }

    /**
     * Set Alumno entity (many to one).
     *
     * @param \Umg\ConferenciaBundle\Entity\Alumno $alumno
     * @return \Umg\ConferenciaBundle\Entity\AlumnoRecuerdo
     */
    public function setAlumno(Alumno $alumno = null)
    {
        $this->alumno = $alumno;

        return $this;
    }

    /**
     * Get Alumno entity (many to one).
     *
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function getAlumno()
    {
        return $this->alumno;
    }

    /**
     * Set Recuerdo entity (many to one).
     *
     * @param \Umg\ConferenciaBundle\Entity\Recuerdo $recuerdo
     * @return \Umg\ConferenciaBundle\Entity\AlumnoRecuerdo
     */
    public function setRecuerdo(Recuerdo $recuerdo = null)
    {
        $this->recuerdo = $recuerdo;

        return $this;
    }

    /**
     * Get Recuerdo entity (many to one).
     *
     * @return \Umg\ConferenciaBundle\Entity\Recuerdo
     */
    public function getRecuerdo()
    {
        return $this->recuerdo;
    }

    /**
     * Set Usuario entity (many to one).
     *
     * @param \Umg\ConferenciaBundle\Entity\Usuario $usuario
     * @return \Umg\ConferenciaBundle\Entity\AlumnoRecuerdo
     */
    public function setUsuario(Usuario $usuario = null)
    {
        $this->usuario = $usuario;

        return $this;
    }

    /**
     * Get Usuario entity (many to one).
     *
     * @return \Umg\ConferenciaBundle\Entity\Usuario
     */
    public function getUsuario()
    {
        return $this->usuario;
    }

    public function __sleep()
    {
        return array('id', 'FechaHora', 'Alumno_id', 'Recuerdo_id', 'Usuario_id');
    }
}