<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-04-27 18:40:59.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\ConferenciaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\ConferenciaBundle\Entity\Alumno
 *
 * @ORM\Entity()
 * @ORM\Table(name="Alumno")
 */
class Alumno
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $Carne;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $Nombre;

    /**
     * @ORM\OneToMany(targetEntity="AlumnoPago", mappedBy="alumno")
     * @ORM\JoinColumn(name="id", referencedColumnName="Alumno_id")
     */
    protected $alumnoPagos;

    /**
     * @ORM\OneToMany(targetEntity="AlumnoRecuerdo", mappedBy="alumno")
     * @ORM\JoinColumn(name="id", referencedColumnName="Alumno_id")
     */
    protected $alumnoRecuerdos;

    /**
     * @ORM\OneToMany(targetEntity="ConferenciaAlumno", mappedBy="alumno")
     * @ORM\JoinColumn(name="id", referencedColumnName="Alumno_id")
     */
    protected $conferenciaAlumnos;

    public function __construct()
    {
        $this->alumnoPagos = new ArrayCollection();
        $this->alumnoRecuerdos = new ArrayCollection();
        $this->conferenciaAlumnos = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Carne.
     *
     * @param string $Carne
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function setCarne($Carne)
    {
        $this->Carne = $Carne;

        return $this;
    }

    /**
     * Get the value of Carne.
     *
     * @return string
     */
    public function getCarne()
    {
        return $this->Carne;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Add AlumnoPago entity to collection (one to many).
     *
     * @param \Umg\ConferenciaBundle\Entity\AlumnoPago $alumnoPago
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function addAlumnoPago(AlumnoPago $alumnoPago)
    {
        $this->alumnoPagos[] = $alumnoPago;

        return $this;
    }

    /**
     * Remove AlumnoPago entity from collection (one to many).
     *
     * @param \Umg\ConferenciaBundle\Entity\AlumnoPago $alumnoPago
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function removeAlumnoPago(AlumnoPago $alumnoPago)
    {
        $this->alumnoPagos->removeElement($alumnoPago);

        return $this;
    }

    /**
     * Get AlumnoPago entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAlumnoPagos()
    {
        return $this->alumnoPagos;
    }

    /**
     * Add AlumnoRecuerdo entity to collection (one to many).
     *
     * @param \Umg\ConferenciaBundle\Entity\AlumnoRecuerdo $alumnoRecuerdo
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function addAlumnoRecuerdo(AlumnoRecuerdo $alumnoRecuerdo)
    {
        $this->alumnoRecuerdos[] = $alumnoRecuerdo;

        return $this;
    }

    /**
     * Remove AlumnoRecuerdo entity from collection (one to many).
     *
     * @param \Umg\ConferenciaBundle\Entity\AlumnoRecuerdo $alumnoRecuerdo
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function removeAlumnoRecuerdo(AlumnoRecuerdo $alumnoRecuerdo)
    {
        $this->alumnoRecuerdos->removeElement($alumnoRecuerdo);

        return $this;
    }

    /**
     * Get AlumnoRecuerdo entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAlumnoRecuerdos()
    {
        return $this->alumnoRecuerdos;
    }

    /**
     * Add ConferenciaAlumno entity to collection (one to many).
     *
     * @param \Umg\ConferenciaBundle\Entity\ConferenciaAlumno $conferenciaAlumno
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function addConferenciaAlumno(ConferenciaAlumno $conferenciaAlumno)
    {
        $this->conferenciaAlumnos[] = $conferenciaAlumno;

        return $this;
    }

    /**
     * Remove ConferenciaAlumno entity from collection (one to many).
     *
     * @param \Umg\ConferenciaBundle\Entity\ConferenciaAlumno $conferenciaAlumno
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function removeConferenciaAlumno(ConferenciaAlumno $conferenciaAlumno)
    {
        $this->conferenciaAlumnos->removeElement($conferenciaAlumno);

        return $this;
    }

    /**
     * Get ConferenciaAlumno entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getConferenciaAlumnos()
    {
        return $this->conferenciaAlumnos;
    }

    public function __sleep()
    {
        return array('id', 'Carne', 'Nombre');
    }
}