<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-16 16:59:51.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\ConferenciaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Umg\ConferenciaBundle\Entity\AlumnoPago
 *
 * @ORM\Entity()
 * @ORM\Table(name="AlumnoPago", indexes={@ORM\Index(name="fk_AlumnoPago_Alumno1_idx", columns={"Alumno_id"}), @ORM\Index(name="fk_AlumnoPago_Evento1_idx", columns={"Evento_id"})})
 */
class AlumnoPago
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $Boleta;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Alumno_id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $Fecha;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Evento_id;

    /**
     * @ORM\ManyToOne(targetEntity="Alumno", inversedBy="alumnoPagos")
     * @ORM\JoinColumn(name="Alumno_id", referencedColumnName="id")
     */
    protected $alumno;

    /**
     * @ORM\ManyToOne(targetEntity="Evento", inversedBy="alumnoPagos")
     * @ORM\JoinColumn(name="Evento_id", referencedColumnName="id")
     */
    protected $evento;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Boleta.
     *
     * @param string $Boleta
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setBoleta($Boleta)
    {
        $this->Boleta = $Boleta;

        return $this;
    }

    /**
     * Get the value of Boleta.
     *
     * @return string
     */
    public function getBoleta()
    {
        return $this->Boleta;
    }

    /**
     * Set the value of Alumno_id.
     *
     * @param integer $Alumno_id
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setAlumnoId($Alumno_id)
    {
        $this->Alumno_id = $Alumno_id;

        return $this;
    }

    /**
     * Get the value of Alumno_id.
     *
     * @return integer
     */
    public function getAlumnoId()
    {
        return $this->Alumno_id;
    }

    /**
     * Set the value of Fecha.
     *
     * @param \DateTime $Fecha
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setFecha($Fecha)
    {
        $this->Fecha = $Fecha;

        return $this;
    }

    /**
     * Get the value of Fecha.
     *
     * @return \DateTime
     */
    public function getFecha()
    {
        return $this->Fecha;
    }

    /**
     * Set the value of Evento_id.
     *
     * @param integer $Evento_id
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setEventoId($Evento_id)
    {
        $this->Evento_id = $Evento_id;

        return $this;
    }

    /**
     * Get the value of Evento_id.
     *
     * @return integer
     */
    public function getEventoId()
    {
        return $this->Evento_id;
    }

    /**
     * Set Alumno entity (many to one).
     *
     * @param \Umg\ConferenciaBundle\Entity\Alumno $alumno
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setAlumno(Alumno $alumno = null)
    {
        $this->alumno = $alumno;

        return $this;
    }

    /**
     * Get Alumno entity (many to one).
     *
     * @return \Umg\ConferenciaBundle\Entity\Alumno
     */
    public function getAlumno()
    {
        return $this->alumno;
    }

    /**
     * Set Evento entity (many to one).
     *
     * @param \Umg\ConferenciaBundle\Entity\Evento $evento
     * @return \Umg\ConferenciaBundle\Entity\AlumnoPago
     */
    public function setEvento(Evento $evento = null)
    {
        $this->evento = $evento;

        return $this;
    }

    /**
     * Get Evento entity (many to one).
     *
     * @return \Umg\ConferenciaBundle\Entity\Evento
     */
    public function getEvento()
    {
        return $this->evento;
    }

    public function __sleep()
    {
        return array('id', 'Boleta', 'Alumno_id', 'Fecha', 'Evento_id');
    }
}