<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-16 11:57:28.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\ConferenciaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Umg\ConferenciaBundle\Entity\Pago
 *
 * @ORM\Entity()
 * @ORM\Table(name="Pago", indexes={@ORM\Index(name="fk_Pago_Conferencista1_idx", columns={"Conferencista_id"}), @ORM\Index(name="fk_Pago_Usuario1_idx", columns={"Usuario_id"})})
 */
class Pago
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $Documento;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $Monto;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Conferencista_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Usuario_id;

    /**
     * @ORM\ManyToOne(targetEntity="Conferencistum", inversedBy="pagos")
     * @ORM\JoinColumn(name="Conferencista_id", referencedColumnName="id")
     */
    protected $conferencistum;

    /**
     * @ORM\ManyToOne(targetEntity="Usuario", inversedBy="pagos")
     * @ORM\JoinColumn(name="Usuario_id", referencedColumnName="id")
     */
    protected $usuario;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\ConferenciaBundle\Entity\Pago
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Documento.
     *
     * @param string $Documento
     * @return \Umg\ConferenciaBundle\Entity\Pago
     */
    public function setDocumento($Documento)
    {
        $this->Documento = $Documento;

        return $this;
    }

    /**
     * Get the value of Documento.
     *
     * @return string
     */
    public function getDocumento()
    {
        return $this->Documento;
    }

    /**
     * Set the value of Monto.
     *
     * @param string $Monto
     * @return \Umg\ConferenciaBundle\Entity\Pago
     */
    public function setMonto($Monto)
    {
        $this->Monto = $Monto;

        return $this;
    }

    /**
     * Get the value of Monto.
     *
     * @return string
     */
    public function getMonto()
    {
        return $this->Monto;
    }

    /**
     * Set the value of Conferencista_id.
     *
     * @param integer $Conferencista_id
     * @return \Umg\ConferenciaBundle\Entity\Pago
     */
    public function setConferencistaId($Conferencista_id)
    {
        $this->Conferencista_id = $Conferencista_id;

        return $this;
    }

    /**
     * Get the value of Conferencista_id.
     *
     * @return integer
     */
    public function getConferencistaId()
    {
        return $this->Conferencista_id;
    }

    /**
     * Set the value of Usuario_id.
     *
     * @param integer $Usuario_id
     * @return \Umg\ConferenciaBundle\Entity\Pago
     */
    public function setUsuarioId($Usuario_id)
    {
        $this->Usuario_id = $Usuario_id;

        return $this;
    }

    /**
     * Get the value of Usuario_id.
     *
     * @return integer
     */
    public function getUsuarioId()
    {
        return $this->Usuario_id;
    }

    /**
     * Set Conferencistum entity (many to one).
     *
     * @param \Umg\ConferenciaBundle\Entity\Conferencistum $conferencistum
     * @return \Umg\ConferenciaBundle\Entity\Pago
     */
    public function setConferencistum(Conferencistum $conferencistum = null)
    {
        $this->conferencistum = $conferencistum;

        return $this;
    }

    /**
     * Get Conferencistum entity (many to one).
     *
     * @return \Umg\ConferenciaBundle\Entity\Conferencistum
     */
    public function getConferencistum()
    {
        return $this->conferencistum;
    }

    /**
     * Set Usuario entity (many to one).
     *
     * @param \Umg\ConferenciaBundle\Entity\Usuario $usuario
     * @return \Umg\ConferenciaBundle\Entity\Pago
     */
    public function setUsuario(Usuario $usuario = null)
    {
        $this->usuario = $usuario;

        return $this;
    }

    /**
     * Get Usuario entity (many to one).
     *
     * @return \Umg\ConferenciaBundle\Entity\Usuario
     */
    public function getUsuario()
    {
        return $this->usuario;
    }

    public function __sleep()
    {
        return array('id', 'Documento', 'Monto', 'Conferencista_id', 'Usuario_id');
    }
}