<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-04-27 18:40:59.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\ConferenciaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\ConferenciaBundle\Entity\Salon
 *
 * @ORM\Entity()
 * @ORM\Table(name="Salon")
 */
class Salon
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $Nombre;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $Cupo;

    /**
     * @ORM\OneToMany(targetEntity="Conferencium", mappedBy="salon")
     * @ORM\JoinColumn(name="id", referencedColumnName="Salon_id")
     */
    protected $conferencia;

    public function __construct()
    {
        $this->conferencia = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\ConferenciaBundle\Entity\Salon
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Umg\ConferenciaBundle\Entity\Salon
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Set the value of Cupo.
     *
     * @param integer $Cupo
     * @return \Umg\ConferenciaBundle\Entity\Salon
     */
    public function setCupo($Cupo)
    {
        $this->Cupo = $Cupo;

        return $this;
    }

    /**
     * Get the value of Cupo.
     *
     * @return integer
     */
    public function getCupo()
    {
        return $this->Cupo;
    }

    /**
     * Add Conferencium entity to collection (one to many).
     *
     * @param \Umg\ConferenciaBundle\Entity\Conferencium $conferencium
     * @return \Umg\ConferenciaBundle\Entity\Salon
     */
    public function addConferencium(Conferencium $conferencium)
    {
        $this->conferencia[] = $conferencium;

        return $this;
    }

    /**
     * Remove Conferencium entity from collection (one to many).
     *
     * @param \Umg\ConferenciaBundle\Entity\Conferencium $conferencium
     * @return \Umg\ConferenciaBundle\Entity\Salon
     */
    public function removeConferencium(Conferencium $conferencium)
    {
        $this->conferencia->removeElement($conferencium);

        return $this;
    }

    /**
     * Get Conferencium entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getConferencia()
    {
        return $this->conferencia;
    }

    public function __sleep()
    {
        return array('id', 'Nombre', 'Cupo');
    }
}